-- ============================================================
-- Saints Station — Real Club Data (from Chartered Clubs Excel)
-- Run in: Supabase Dashboard → SQL Editor → New Query
-- WARNING: Replaces all existing fictional club data
-- ============================================================

-- 1. Clear existing fictional data
DELETE FROM public.club_updates;
DELETE FROM public.clubs;

-- 2. Insert real chartered clubs

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('ai-club', 'AI Club', 'engineering', 'Build the future with artificial intelligence.', 'AI Club explores machine learning, neural networks, and real-world AI applications. Members work on hands-on projects, discuss cutting-edge AI research, and compete in AI-focused challenges. Open to all experience levels.', 'Mr. Kessler', 'kesslerv@bsd405.org', 'Mondays', '3:30–4:30 PM', 'Portable 1', ARRAY['Open to all grades and experience levels'], 'Show up to any Monday meeting in Portable 1.', 'aiclub.interlake@gmail.com', 0, false, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('badminton-club', 'Badminton Club', 'service', 'Rally, smash, repeat.', 'Badminton Club offers students a chance to learn and compete in badminton in a fun, welcoming environment. Members of all skill levels are welcome — from first-timers to experienced players.', 'Michael Netherton', 'NethertonM@bsd405.org', 'Wednesdays', '1:00–2:00 PM', 'Main Gym', ARRAY['Open to all grades and skill levels'], 'Come to any Wednesday lunch meeting in the Main Gym.', 'gsyoulan@gmail.com', 0, false, '[{"name": "Youlan Wang", "role": "Co-President", "email": "s-wangyo@bsd405.org"}, {"name": "Manas Jain", "role": "Co-President", "email": "s-jainman@bsd405.org"}, {"name": "Stanley Song", "role": "Co-President", "email": "s-songs@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('biology-club', 'Biology Club', 'science', 'Explore life at every scale.', 'Biology Club dives deep into the living world — from cell biology and genetics to ecology and human physiology. Members participate in labs, discussions, and biology competitions throughout the year.', 'Philip Allen', 'allenp@bsd405.org', 'Thursdays', '3:30–4:00 PM', 'Mr. Allen''s Room', ARRAY['Open to all grades'], 'Drop in to any Thursday meeting in Mr. Allen''s room.', 'interlakebiologyclub@gmail.com', 0, false, '[{"name": "Weiyu Tsay", "role": "Co-President", "email": "s-tsayw@bsd405.org"}, {"name": "Jason Casino", "role": "Co-President", "email": "s-casinoj@bsd405.org"}, {"name": "Arnav Doreswamy", "role": "General Officer", "email": "s-doreswamya@bsd405.org"}, {"name": "Sarvesh Raghuraman", "role": "General Officer", "email": "s-raghuramans@bsd405.org"}, {"name": "Tori Hulverson", "role": "General Officer", "email": "s-hulversonv@bsd405.org"}, {"name": "Sezim Abdukhalieva", "role": "General Officer", "email": "s-abdukhalievas@bsd405.org"}, {"name": "Sofia Matveevici", "role": "General Officer", "email": "s-matveevicis@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('biotech-club', 'Biotech Club', 'science', 'Where biology meets technology.', 'Biotech Club explores the intersection of biology and technology — from CRISPR and synthetic biology to medical devices and bioinformatics. Members engage in projects, research discussions, and guest speaker events.', 'Philip Allen', 'allenp@bsd405.org', 'Mondays', '3:30–4:00 PM', 'Mr. Allen''s Classroom', ARRAY['Open to all grades'], 'Come to any Monday meeting in Mr. Allen''s classroom.', 'interlake.biotechclub@gmail.com', 0, false, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('bird-club', 'Bird Club', 'science', 'Discover the birds in your backyard and beyond.', 'Bird Club (Ornithology) introduces students to the study of birds through field observations, species identification, and conservation discussions. We explore local ecosystems and Washington state''s diverse birdlife.', 'Ms. Kujawa', 'kujawac@bsd405.org', 'Every other Thursday', '3:30–4:00 PM', 'Kujawa''s Portable', ARRAY['Open to all grades — no experience needed'], 'Show up to any meeting in Ms. Kujawa''s portable.', 'ihs.ornithology@gmail.com', 0, false, '[{"name": "Zihan Zhao", "role": "President", "email": "s-zhaozih@bsd405.org"}, {"name": "Jenny Shen", "role": "Vice President", "email": "s-shenjen@bsd405.org"}, {"name": "Sebastian Shaffer", "role": "Outreach", "email": "s-shaffers@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('chess-club', 'Chess Club', 'leadership', 'Think ahead. Play smart.', 'Chess Club welcomes players from beginner to advanced. Members improve their game through practice, strategy sessions, and KingCo tournaments. Competitive players can represent Interlake at regional chess championships.', 'Caroline Wright', 'WrightCa@bsd405.org', 'Mondays', '3:30–4:30 PM (KingCo days until 6:30)', 'Library', ARRAY['Open to all grades and skill levels'], 'Come to any Monday meeting in the library.', 's-ramaswamyr@bsd405.org', 0, false, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('creative-sketchbook-society', 'Creative Sketchbook Society', 'creative', 'Fill the page. Find your voice.', 'Creative Sketchbook Society is a low-pressure art space where students draw, sketch, and explore visual storytelling. Members work in any medium — pencil, ink, watercolor, or digital — and share their work in a supportive community.', 'Reggie Friedle', 'friedler@bsd405.org', 'Tuesdays', '3:30–4:00 PM', 'Room 1522', ARRAY['Open to all grades — any skill level welcome'], 'Drop by Room 1522 on any Tuesday.', 's-chawlas@bsd405.org', 0, false, '[{"name": "Sneha Chawla", "role": "President", "email": "s-chawlas@bsd405.org"}, {"name": "Sara Baher", "role": "Vice President", "email": "s-bahers@bsd405.org"}, {"name": "Claire Lee", "role": "Secretary", "email": "s-leecl@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('deca', 'DECA', 'leadership', 'Prepare for careers in business and marketing.', 'DECA prepares emerging leaders and entrepreneurs for careers in marketing, finance, hospitality, and management. Members compete at district, state, and international DECA conferences through role-plays and business presentations.', 'Aric Weiker & Richard Chamberlain', 'weikera@bsd405.org', 'Tuesdays', '3:30–4:30 PM', 'Room 1806', ARRAY['Open to all grades'], 'Come to any Tuesday meeting in Room 1806 (Mr. Weiker''s classroom).', 's-davids@bsd405.org', 0, false, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('fiber-club', 'Fiber Club', 'creative', 'Knit, crochet, and create.', 'Fiber Club is a relaxed creative space for students who enjoy knitting, crocheting, embroidery, weaving, or any other fiber arts. All skill levels welcome — bring your own project or learn from scratch.', 'Reggie Friedle', 'friedler@bsd405.org', 'Wednesdays', '1:00–2:00 PM', 'TBD', ARRAY['Open to all grades — no experience needed'], 'Come to any Wednesday lunch meeting.', 's-featherlyv@bsd405.org', 0, false, '[{"name": "Veronica Featherly", "role": "President", "email": "s-featherlyv@bsd405.org"}, {"name": "Fiona Duncan", "role": "Vice President", "email": "s-duncanf@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('film-competition-creative-media', 'Film Competition and Creative Media Club', 'creative', 'Script it. Shoot it. Submit it.', 'Film Competition and Creative Media Club produces short films for regional and national competitions. Members write screenplays, direct, film, and edit — gaining real production experience from pre-production through final cut.', 'Alex Glover', 'glovera@bsd405.org', 'Every other Monday', '3:30–4:00 PM', 'Room 1406', ARRAY['Open to all grades'], 'Come to any meeting in Room 1406.', 'filmcompetitionclub@gmail.com', 0, false, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('fps', 'FPS (Future Problem Solvers)', 'leadership', 'Solve tomorrow''s problems today.', 'Future Problem Solvers (FPS) trains students in creative and critical thinking through structured problem-solving competitions. Teams analyze complex real-world scenarios, brainstorm solutions, and present action plans at state competitions.', 'Claire Kujawa', 'kujawac@bsd405.org', 'Fridays', '3:30–4:00 PM', 'Portable 7', ARRAY['Open to all grades'], 'Come to any Friday meeting in Portable 7.', 's-davids@bsd405.org', 0, false, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('french-club', 'French Club', 'cultural', 'Parlez-vous français? Come find out.', 'French Club celebrates the French language and Francophone cultures through conversation practice, films, food, and cultural events. Open to all students — whether you''re in French class or just curious about the language.', 'Madame Collomb', 'collombs@bsd405.org', 'Thursdays', '3:30 PM', 'TBD', ARRAY['Open to all grades — no French required'], 'Come to any Thursday meeting.', 's-fernandezo@bsd405.org', 0, false, '[{"name": "Olivia Fernandez Mommer", "role": "Co-President", "email": "s-fernandezo@bsd405.org"}, {"name": "Helena Hernandez Palacio", "role": "Co-President", "email": "s-hernandezhel@bsd405.org"}, {"name": "Celeste Perdrizet", "role": "Vice President", "email": "s-perdrizetc@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('future-farmers-of-america', 'Future Farmers of America', 'service', 'Growing leaders in agriculture and life science.', 'FFA develops members'' potential for premier leadership, personal growth, and career success through agricultural education. Interlake FFA participates in competitions, community projects, and state FFA events.', 'Lisa Lindholm', 'lindholml@bsd405.org', 'Thursdays', '3:30 PM', 'Room L1', ARRAY['Open to all grades'], 'Come to any Thursday meeting in Room L1.', 's-marellas@bsd405.org', 0, false, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('girls-who-code', 'Girls Who Code', 'engineering', 'Close the gender gap in tech — one line at a time.', 'Girls Who Code empowers young women to pursue careers in computer science and technology. Members learn coding skills, work on projects, and connect with a community of women in tech through events and mentorship.', 'Emily Atar', 'atare@bsd405.org', 'Mondays', '3:30–4:00 PM', 'Room 1802', ARRAY['Open to all students interested in coding and tech'], 'Come to any Monday meeting in Room 1802.', 's-nambia@bsd405.org', 0, true, '[{"name": "Akshaya Nambi", "role": "President", "email": "s-nambia@bsd405.org"}, {"name": "Aishwarya Nambi", "role": "Vice President", "email": "s-nambiai@bsd405.org"}, {"name": "Isha Mehta", "role": "Secretary", "email": "mehtai@bsd405.org"}, {"name": "Anika Gupta", "role": "Outreach", "email": "guptaanik@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('hosa', 'HOSA – Future Health Professionals', 'science', 'Developing tomorrow''s health care leaders.', 'HOSA prepares students for careers in health science through competitive events, community service, and health education. Members compete at state and national HOSA conferences in areas like clinical nursing, biomedical debate, and health career displays.', 'Christopher Alvarez', 'alvarezc@bsd405.org', 'Tuesdays', '3:30–4:30 PM', 'Room 1', ARRAY['Open to all grades — interest in health sciences recommended'], 'Come to any Tuesday meeting.', 'interlakehosa@gmail.com', 0, false, '[{"name": "Parineeta Kapoor", "role": "Co-President", "email": "s-kapoorp@bsd405.org"}, {"name": "Dhanush Dani", "role": "Co-President", "email": "s-danid@bsd405.org"}, {"name": "Liba Mujtaba", "role": "General Officer", "email": "s-mujtabal@bsd405.org"}, {"name": "Aiden Aquino", "role": "General Officer", "email": "s-aquinoa@bsd405.org"}, {"name": "Olivia Fernandez Mommer", "role": "General Officer", "email": "s-fernandezo@bsd405.org"}, {"name": "Tarang Yadav", "role": "General Officer", "email": "s-yadavta@bsd405.org"}, {"name": "Anushka Elango", "role": "Appointed Officer", "email": "s-elangoa@bsd405.org"}, {"name": "Danielle Bar", "role": "Appointed Officer", "email": "s-bard@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('jewish-student-association', 'Jewish Student Association', 'cultural', 'Community, culture, and conversation.', 'JSA creates a welcoming space for Jewish students and allies to celebrate culture, discuss current events, and build community. We meet monthly for conversations, holiday celebrations, and social events.', 'Christopher Alvarez', 'alvarezc@bsd405.org', 'Monthly (Mondays or Tuesdays)', 'TBD', 'Mr. Alvarez''s Room', ARRAY['Open to all students'], 'Come to any monthly meeting in Mr. Alvarez''s room.', 's-egozin@bsd405.org', 0, false, '[{"name": "Noam Egozi", "role": "President", "email": "s-egozin@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('makers-club', 'Maker''s Club', 'engineering', 'If you can imagine it, you can build it.', 'Maker''s Club is a hands-on engineering and fabrication space where students design, prototype, and build. Members work with electronics, 3D printing, woodworking, and more — bringing creative ideas to life.', 'Mr. Ramsay', 'RamsayB@bsd405.org', 'Thursdays', '3:30–4:00 PM', 'Portable 2', ARRAY['Open to all grades and skill levels'], 'Come to any Thursday meeting in Portable 2.', 'kennethcyli@gmail.com', 0, false, '[{"name": "Kenneth Li", "role": "President", "email": "s-lik@bsd405.org"}, {"name": "Yug Maheshwari", "role": "Officer", "email": "s-maheshwariy@bsd405.org"}, {"name": "Aarav Vaswani", "role": "Officer", "email": "s-vaswania@bsd405.org"}, {"name": "Aidan Graham", "role": "Officer", "email": "s-grahama@bsd405.org"}, {"name": "Hamza Abdalla", "role": "Officer", "email": "s-abdallah@bsd405.org"}, {"name": "Bera Sir", "role": "Officer", "email": "s-sirb@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('math-club', 'Math Club', 'engineering', 'Solve harder problems.', 'Math Club competes in AMC 10/12, AIME, and Washington state math competitions. Members study advanced topics — combinatorics, number theory, algebra, and geometry — and prepare for prestigious national mathematics contests.', 'Meribeth Nordloef Pedersen', 'nordloefm@bsd405.org', 'Tuesdays', '3:30–4:15 PM', 'Testing Center', ARRAY['Open to all grades and skill levels'], 'Come to any Tuesday meeting in the Testing Center.', 'interlakemathclub@gmail.com', 0, true, '[{"name": "Evan Cen", "role": "Co-President", "email": "s-cene@bsd405.org"}, {"name": "Ian Rui", "role": "Co-President", "email": "s-ruii@bsd405.org"}, {"name": "Anwen Li", "role": "Officer", "email": "s-lianw@bsd405.org"}, {"name": "Elena Arkhipova", "role": "Officer", "email": "s-arkhipovae@bsd405.org"}, {"name": "Jai Mukherjee", "role": "Officer", "email": "s-mukherjeej@bsd405.org"}, {"name": "Zexu Li", "role": "Officer", "email": "s-lize@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('mock-trial', 'Mock Trial', 'diplomatic', 'Argue the case. Win the room.', 'Mock Trial prepares students for simulated courtroom competitions where they play the roles of attorneys and witnesses. Members develop legal reasoning, public speaking, and persuasive argumentation skills at regional and state tournaments.', 'Stacia Hansford', 'hansfords@bsd405.org', 'Fridays (+ occasional Mondays)', '4:00–5:00 PM', 'Library', ARRAY['Open to all grades'], 'Come to any Friday meeting in the library.', 's-judgec@bsd405.org', 0, false, '[{"name": "Cadence Judge", "role": "President", "email": "s-judgec@bsd405.org"}, {"name": "Avery Morris", "role": "President", "email": "s-morrisa@bsd405.org"}, {"name": "Quincy Ricker", "role": "President", "email": "s-rickerq@bsd405.org"}, {"name": "Jaydaa Morsy", "role": "Vice President", "email": "s-morsyj@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('model-un', 'Model United Nations', 'diplomatic', 'Debate global issues. Forge solutions.', 'Model UN simulates the United Nations, with members acting as country delegates in committee debates on global topics. Members research international issues, write position papers, and compete at regional and national MUN conferences.', 'Amalia Ramos', 'ramosa@bsd405.org', 'Mondays', '3:30–4:00 PM', 'Ms. Ramos''s Room', ARRAY['Open to all grades'], 'Come to any Monday meeting in Ms. Ramos''s room.', 'interlakemodelun@gmail.com', 0, true, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('philosophy-club', 'Philosophy Club', 'diplomatic', 'Question everything. Think deeper.', 'Philosophy Club explores fundamental questions about existence, knowledge, ethics, and reality. Members engage in Socratic discussions, read philosophical texts, and debate ideas ranging from ancient Greece to contemporary thought.', 'Alexander Garcia', 'garciaal@bsd405.org', 'Every other Tuesday', '3:30–4:00 PM', 'Room 1705', ARRAY['Open to all grades — come ready to think and discuss'], 'Come to any bi-weekly Tuesday meeting in Room 1705.', 's-morrisa@bsd405.org', 0, false, '[{"name": "Max Schuringa", "role": "Co-President", "email": "s-schuringam@bsd405.org"}, {"name": "Avery Morris", "role": "Co-President", "email": "s-morrisa@bsd405.org"}, {"name": "Venkata Siddharth Pendyala", "role": "Co-President", "email": "s-pendyalas@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('red-cross', 'Red Cross Club', 'service', 'Give blood, give time, save lives.', 'Red Cross Club organizes blood drives, disaster preparedness training, and community health initiatives in partnership with the American Red Cross. Members lead life-saving campaigns and volunteer at community health events throughout the year.', 'Lindzee Alvarez', 'alvarezl@bsd405.org', 'Every other Thursday', '3:30–4:15 PM', 'Room 1702', ARRAY['Open to all grades'], 'Come to any bi-weekly Thursday meeting in Room 1702.', 'aanyabansal.27@gmail.com', 0, false, '[{"name": "Aanya Bansal", "role": "President", "email": "s-bansalaa@bsd405.org"}, {"name": "Akshita Shebe", "role": "Vice President", "email": "s-shebea@bsd405.org"}, {"name": "Jessica Yang", "role": "Secretary", "email": "s-yangje@bsd405.org"}, {"name": "Olivia Wang", "role": "Treasurer", "email": "s-wangoli@bsd405.org"}, {"name": "Kailani Fernandez", "role": "Media Manager", "email": "s-fernandezk@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('research-science-fair', 'Research and Science Fair Club', 'science', 'Do real science. Win real awards.', 'Research and Science Fair Club guides students through the scientific research process — from forming hypotheses to presenting at science fairs. Members compete at regional and state science fairs and the Washington State Science & Engineering Fair.', 'Phillip Allen', 'allenp@bsd405.org', 'Fridays', '3:30–4:00 PM', 'Mr. Allen''s Room', ARRAY['Open to all grades — curiosity and commitment to research required'], 'Come to any Friday meeting in Mr. Allen''s room.', 's-kompellaki@bsd405.org', 0, false, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('robotics', 'Robotics', 'engineering', 'Build, code, compete.', 'Saints Robotics participates in the FIRST Robotics Competition (FRC). Members design, build, program, and operate competition robots across sub-teams covering mechanical engineering, electrical systems, software, and outreach. We compete at regional and state-level tournaments.', 'Sandrine Collomb', 'collombs@bsd405.org', 'Mondays & Fridays', '3:45–5:45 PM', 'Ivanhoe', ARRAY['Open to all grades', 'Sub-teams available for all skills: mechanical, electrical, software, and business', 'High attendance commitment during build season'], 'Email leadership@saintsrobotics.com or show up to any Monday or Friday meeting in Ivanhoe.', 'leadership@saintsrobotics.com', 0, true, '[{"name": "Olivia Park", "role": "President", "email": "s-parko@bsd405.org"}, {"name": "Aarav Vaswani", "role": "Vice President", "email": "s-vaswania@bsd405.org"}, {"name": "Jasper Duan", "role": "Secretary", "email": "s-duanja@bsd405.org"}, {"name": "Jessica Yang", "role": "Treasurer", "email": "s-yangje@bsd405.org"}, {"name": "Hamza Abdalla", "role": "Director of Engineering", "email": "s-abdallah@bsd405.org"}, {"name": "Aidan Graham", "role": "Director of Engineering", "email": "s-grahama@bsd405.org"}, {"name": "Mathew Zhou", "role": "Director of Communications", "email": "s-zhouma@bsd405.org"}, {"name": "Ava Anklesaria", "role": "Director of Competition", "email": "s-anklesariaa@bsd405.org"}, {"name": "Evan Cen", "role": "Director of Competition", "email": "s-cene@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('rocketry-club', 'Rocketry Club', 'engineering', 'Launch higher every time.', 'Rocketry Club designs, builds, and launches model rockets while exploring the science of flight and propulsion. Members compete in national rocketry competitions, including the American Rocketry Challenge, and have represented Interlake at nationals.', 'Lisa Dossett', 'dossettl@bsd405.org', 'Tuesdays', '3:30–4:15 PM', 'Room 1710', ARRAY['Open to all grades'], 'Come to any Tuesday meeting in Room 1710.', 'interlakerocketryclub@gmail.com', 0, false, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('school-newspaper', 'School Newspaper — Interlake Inquirer', 'creative', 'Report it. Write it. Publish it.', 'The Interlake Inquirer is the student-run newspaper covering campus news, sports, arts, opinions, and features. Staff reporters, photographers, and editors produce digital and print editions throughout the year.', 'Christopher Alvarez', 'alvarezc@bsd405.org', 'Wednesdays', '1:00–1:30 PM', 'Room 1702', ARRAY['Open to all grades — writing, photography, and design experience a plus'], 'Come to any Wednesday lunch meeting in Room 1702.', 'leslie.park0407@gmail.com', 0, false, '[{"name": "Leslie Park", "role": "Editor-in-Chief", "email": "s-parkle@bsd405.org"}, {"name": "Richard Hao", "role": "Editor-in-Chief", "email": "s-haor@bsd405.org"}, {"name": "Willy Du", "role": "Officer", "email": "s-duw@bsd405.org"}, {"name": "Stella Kendrick", "role": "Officer", "email": "s-kendricks@bsd405.org"}, {"name": "Drew Hayden", "role": "Officer", "email": "s-haydend@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('science-club', 'Science Club', 'science', 'Experiment. Discover. Repeat.', 'Science Club runs hands-on experiments, science demos, and exploration activities beyond the classroom curriculum. Members try experiments in chemistry, physics, biology, and earth science in a fun, low-pressure environment.', 'Michael O''Byrne', 'obyrnem@bsd405.org', 'Fridays', '3:30–4:15 PM', 'Room 1610 (Mr. O''Byrne)', ARRAY['Open to all grades — curiosity required, lab coat optional'], 'Come to any Friday meeting in Mr. O''Byrne''s room (1610).', 'scienceclubinterlake@gmail.com', 0, false, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('science-olympiad', 'Science Olympiad', 'science', '23 events. One team.', 'Science Olympiad is a competitive STEM team where students compete in 23 events spanning biology, chemistry, physics, earth science, and engineering. Members specialize in events and collaborate to earn trophies at invitational, regional, and state tournaments.', 'Julie Tzucker', 'tzuckerj@bsd405.org', 'Mondays', '3:30–4:30 PM', 'Room 1704', ARRAY['Tryouts in September — open to all grades', 'Competitive team of 15 members + alternates'], 'Try out in September. Follow our Instagram for tryout announcements.', 'interlakescienceolympiad@gmail.com', 0, true, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('skills-usa-builders', 'Skills USA Builders Club', 'engineering', 'Build with your hands. Compete with your skills.', 'Skills USA Builders Club gives students real-world experience in construction, woodworking, and skilled trades. Members build projects, compete in Skills USA competitions, and develop practical craftsmanship skills valued in engineering and construction careers.', 'William Selset', 'selsetw@bsd405.org', 'Thursdays', '3:30–4:30 PM', 'Woodshop', ARRAY['Open to all grades'], 'Come to any Thursday meeting in the Woodshop.', 's-blackc@bsd405.org', 0, false, '[{"name": "Clark Black", "role": "President", "email": "s-blackc@bsd405.org"}, {"name": "Om Sansare", "role": "Vice President", "email": "s-sansareo@bsd405.org"}, {"name": "Finn Volynsky-Pouliotte", "role": "Secretary", "email": "s-volynskyf@bsd405.org"}, {"name": "Taiga Vickers", "role": "Treasurer", "email": "s-vickerst@bsd405.org"}, {"name": "Aaroh Kandhare", "role": "HR", "email": "s-kandharea@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('skin-science-club', 'Skin Science Club', 'science', 'The science behind healthy skin.', 'Skin Science Club explores dermatology, cosmetic chemistry, and the biology of skin health. Members learn about skincare ingredients, skin conditions, and the science behind common products through presentations, labs, and guest speakers.', 'Ethan Purcell', 'PurcellE@bsd405.org', 'Fridays', '3:30 PM', 'Room 1708', ARRAY['Open to all grades'], 'Come to any Friday meeting in Room 1708.', 's-sorokinas@bsd405.org', 0, false, '[{"name": "Sophy Sorokina", "role": "President"}, {"name": "Nihitha Nadimpalli", "role": "Vice President"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('speech-and-debate', 'Speech and Debate', 'diplomatic', 'Find your voice. Win the argument.', 'Interlake Speech and Debate competes in Lincoln-Douglas, Public Forum, and speech events at NSDA-sanctioned tournaments across Washington. Members develop research, argumentation, rebuttal, and public speaking skills through regular practice rounds.', 'Daniel Garepis-Holland', 'garepishollandd@bsd405.org', 'Tuesdays & Thursdays', '3:30–5:30 PM', 'Library', ARRAY['Open to all grades', 'New members complete an orientation before competing'], 'Come to any Tuesday or Thursday meeting in the library.', 'info@interlakesnd.org', 0, true, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('thespians-club', 'Thespians Club', 'creative', 'Take the stage.', 'Interlake Thespians (International Thespian Society Chapter) produces theatrical performances and develops student artists in acting, directing, and stagecraft. Members perform in productions, attend workshops, and build a lifelong community through theatre.', 'Alexander Glover', 'glovera@bsd405.org', 'Wednesdays', '12:45 PM', 'TBD', ARRAY['Open to all grades'], 'Come to any Wednesday lunch meeting.', 's-marellas@bsd405.org', 0, false, '[{"name": "Sahasra Marella", "role": "President"}, {"name": "Arjun Anand", "role": "Vice President"}, {"name": "Shruthi Raman", "role": "Secretary"}, {"name": "Claire Danley", "role": "Treasurer"}, {"name": "Emma Richardson", "role": "Tech Rep"}, {"name": "Jhonen Burbank", "role": "Social Media / Historian"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('womens-health-healing-harmony', 'Women''s Health / Healing Harmony', 'service', 'Wellness, community, and empowerment.', 'Women''s Health / Healing Harmony creates a space for students to learn about women''s health, wellness, and self-care through discussions, workshops, and community events. We explore physical, mental, and emotional health in an inclusive environment.', 'Alexander Garcia & Lindzee Alvarez', 'GARCIAAL@bsd405.org', 'Every other Tuesday (Garcia) & every other Monday (Alvarez)', '3:30–4:00 PM', 'Room 1705 / Room 1801', ARRAY['Open to all students'], 'Come to any meeting — alternates weekly between Mr. Garcia''s room (Tues) and Ms. Alvarez''s room (Mon).', 's-dasaha@bsd405.org', 0, false, '[{"name": "Ahana Das", "role": "Co-President", "email": "s-dasaha@bsd405.org"}, {"name": "Yana Nath", "role": "Co-President", "email": "s-nathy@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('writing-club', 'Writing Club', 'creative', 'Put it into words.', 'Writing Club is a creative community for students who love to write — fiction, poetry, screenplays, personal essays, and more. Members workshop their writing, share drafts, and support each other in developing a genuine writing practice.', 'Claire Kujawa', 'kujawac@bsd405.org', 'Mondays', '3:30–4:00 PM', 'Portable 7', ARRAY['Open to all grades — any genre, any skill level'], 'Come to any Monday meeting in Portable 7.', 's-deschenesa@bsd405.org', 0, false, '[]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('yearbook', 'Yearbook Club', 'creative', 'Document the year. Tell the story.', 'Yearbook Club produces the annual Interlake yearbook — capturing school life through photography, design, writing, and layout. The editorial board manages production from theme development to final print.', 'Lori Hanson', 'hansonlo@bsd405.org', 'Wednesdays', '1:00–2:00 PM', 'Room 1809', ARRAY['Open to all grades — photography, writing, or design interest helpful'], 'Come to any Wednesday lunch meeting in Room 1809.', 'interlake.yearbook@bsd405.org', 0, false, '[{"name": "Vedika Hemani", "role": "Co-President / Editor-in-Chief", "email": "s-hemaniv@bsd405.org"}, {"name": "Sophie Stonehocker", "role": "Co-President / Editor-in-Chief", "email": "s-stonehockers@bsd405.org"}, {"name": "Sahasra Marella", "role": "Editorial Board", "email": "s-marellas@bsd405.org"}, {"name": "Paige Jacobson", "role": "Editorial Board", "email": "s-jacobsonp@bsd405.org"}, {"name": "Nia Dhillon", "role": "Editorial Board", "email": "s-dhillonni@bsd405.org"}, {"name": "Shruthi Raman", "role": "Editorial Board", "email": "s-ramanshr@bsd405.org"}, {"name": "Ianne Park", "role": "Editorial Board", "email": "s-parkia@bsd405.org"}, {"name": "Melody Qi", "role": "Editorial Board", "email": "s-qil@bsd405.org"}, {"name": "Phoebe Guattare", "role": "Editorial Board", "email": "s-guattarep@bsd405.org"}, {"name": "Arianna Cociug", "role": "Editorial Board", "email": "s-cociuga@bsd405.org"}, {"name": "Sharon Wang", "role": "Editorial Board", "email": "s-wangs@bsd405.org"}]'::jsonb);

INSERT INTO public.clubs (id, name, category, tagline, description, advisor, advisor_email, meeting_days, meeting_time, meeting_location, requirements, how_to_join, contact_email, members, featured, officers)
VALUES ('youth-legislation', 'Youth Legislation', 'diplomatic', 'Draft the law. Debate the future.', 'Youth Legislation teaches students how laws are made by having them write, sponsor, and debate real legislation. Members participate in Youth Legislature simulations at the state level, developing skills in civic engagement, public policy, and public speaking.', 'Alex Glover', 'glovera@bsd405.org', 'Every other Monday', '3:30–4:00 PM', 'Mr. Glover''s Room', ARRAY['Open to all grades'], 'Come to any bi-weekly Monday meeting in Mr. Glover''s room.', 's-vontelav@bsd405.org', 0, false, '[{"name": "Vaishvi Reddy Vontela", "role": "President", "email": "s-vontelav@bsd405.org"}]'::jsonb);